.PHONY: build run clean test

# The default target of this Makefile is build which builds the project.
default: build

# to compile the project, type 'make build'
build:
	cargo build

# To run the project, type 'make run'
run: build
	cargo run

# To clean the project, type 'make clean'
clean:
	cargo clean

# To test the project, type 'make test'
test:
	cargo test